/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package empleadosdao.interfaz;

import empleadosdao.clases.Empleado;
import java.util.ArrayList;
import javax.swing.JList;
import javax.swing.JScrollPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author David
 */
public class PanelListaEmpleados extends javax.swing.JPanel {

      
    
    private InterfazEmpleadosDAO principal;
    /**
     * Creates new form PanelListaEmpleados
     */
    public PanelListaEmpleados(InterfazEmpleadosDAO ventana) {
        principal = ventana;
        
        listaEmpleados = new JList();
        listaEmpleados.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        listaEmpleados.addListSelectionListener((ListSelectionListener) this);
        jScrollPane1 = new JScrollPane();
        jScrollPane1.setViewportView(listaEmpleados);
        initComponents();
    }
    
    public void refrescarLista( ){
        listaEmpleados.setListData(principal.darEmpleados().toArray());
    }
    
    public Empleado darEmpleadoSeleccionado(){
        return (Empleado) listaEmpleados.getSelectedValue();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listaEmpleados = new javax.swing.JList();

        listaEmpleados.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listaEmpleados);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList listaEmpleados;
    // End of variables declaration//GEN-END:variables
}
